import Head from 'next/head'
import {SignedIn, SignedOut, SignInButton, UserButton} from "@clerk/nextjs";

export default function Home() {
    return (
        <div className='p-2'>
            <Head>
                <title>Screen Stash</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <header className='flex justify-between'>
                <h1>Screen Stash</h1>
                <SignedOut>
                    <SignInButton redirectUrl='/dashboard'/>
                </SignedOut>
                <SignedIn>
                    <UserButton signInUrl='/sign-in' showName={true} afterSignOutUrl='/'
                                afterMultiSessionSingleSignOutUrl='/' afterSwitchSessionUrl='/dashboard'
                                userProfileUrl='/profile'/>
                </SignedIn>
            </header>
            <main className='w-full h-full flex gap-8 items-center justify-center'>
                Hello Homepage!
            </main>
        </div>
    )
}
